// ─── Demo data only ────────────────────────────────────────────────────────
// All values are static mock data for UI demonstration purposes.
// Live data integrations are planned for a future release.

export const mockKpis = [
  { label: "BTC Price",        value: "$67,420",       change: "+2.14% (1h)",   positive: true  },
  { label: "ETH Price",        value: "$3,512",        change: "+1.83% (1h)",   positive: true  },
  { label: "SOL Price",        value: "$158.40",       change: "-0.62% (1h)",   positive: false },
  { label: "HYPE Price",       value: "$28.74",        change: "+5.31% (1h)",   positive: true  },
  { label: "Top Ask Wall",     value: "$68,000",       change: "BTC · 95% intensity", positive: null },
  { label: "Fear & Greed",     value: "72 — Greed",   change: "↑ from 65 yesterday", positive: true },
];

export const mockSetups = [
  {
    symbol: "BTCUSDT",
    bias: "LONG",
    confidence: 84,
    entry: "67,100",
    target: "69,500",
    stop: "66,200",
    reason: "Strong bid wall near $67,350 held twice. Spread tight, imbalance +0.42. Breakout watch above $67,500.",
    tags: ["Bid Wall", "Tight Spread", "CVD+"],
  },
  {
    symbol: "ETHUSDT",
    bias: "SHORT",
    confidence: 68,
    entry: "3,540",
    target: "3,380",
    stop: "3,610",
    reason: "Ask wall absorbing buyers near $3,550 resistance. Funding slightly positive — potential long squeeze.",
    tags: ["Ask Wall", "Resistance", "Funding+"],
  },
  {
    symbol: "SOLUSDT",
    bias: "NEUTRAL",
    confidence: 55,
    entry: "—",
    target: "—",
    stop: "—",
    reason: "Balanced order book with no clear directional edge. Watch for a liquidity sweep below $155 before re-entry.",
    tags: ["Balanced Book", "Wait"],
  },
  {
    symbol: "HYPEUSDT",
    bias: "LONG",
    confidence: 71,
    entry: "27.90",
    target: "31.50",
    stop: "26.40",
    reason: "High momentum. Elevated liquidation risk above $30. Enter only on confirmed bid absorption, not chase.",
    tags: ["Momentum", "High Risk", "Liq. Risk"],
  },
];

export const mockWhaleAlerts = [
  {
    id: 1,
    time: "14:32",
    symbol: "BTC",
    side: "BUY",
    size: "$4.2M",
    exchange: "Binance",
    leverage: "3×",
    type: "Futures Long",
    risk: "HIGH",
    confidence: 91,
    reason: "Aggressive long opened near bid wall support at $67,350.",
    action: "Watch for follow-through above $67,500 within 15m.",
  },
  {
    id: 2,
    time: "14:28",
    symbol: "HYPE",
    side: "BUY",
    size: "$2.6M",
    exchange: "Bybit",
    leverage: "10×",
    type: "Perp Long",
    risk: "HIGH",
    confidence: 78,
    reason: "High leverage long cluster forming near $28. Elevated liquidation risk if price drops to $26.40.",
    action: "Do not chase. Wait for bid wall confirmation.",
  },
  {
    id: 3,
    time: "14:21",
    symbol: "ETH",
    side: "SELL",
    size: "$1.8M",
    exchange: "Bybit",
    leverage: "5×",
    type: "Perp Short",
    risk: "MEDIUM",
    confidence: 74,
    reason: "Ask wall absorbing buyers near $3,550 resistance. Short open signals bearish conviction.",
    action: "Monitor for price rejection below $3,540.",
  },
  {
    id: 4,
    time: "14:15",
    symbol: "BTC",
    side: "BUY",
    size: "$6.1M",
    exchange: "OKX",
    leverage: "2×",
    type: "Futures Long",
    risk: "HIGH",
    confidence: 88,
    reason: "Second large long in 20 minutes. Cluster suggests institutional accumulation near $67k.",
    action: "Trend confirmation if price holds above $67,350.",
  },
  {
    id: 5,
    time: "14:08",
    symbol: "SOL",
    side: "SELL",
    size: "$940K",
    exchange: "Binance",
    leverage: "1×",
    type: "Spot Sell",
    risk: "MEDIUM",
    confidence: 62,
    reason: "Spot distribution after failed breakout attempt above $160. Sell pressure increasing.",
    action: "Watch $155 support. Breach confirms short-term bearish.",
  },
  {
    id: 6,
    time: "14:02",
    symbol: "ETH",
    side: "BUY",
    size: "$2.2M",
    exchange: "Binance",
    leverage: "1×",
    type: "Spot Accumulation",
    risk: "LOW",
    confidence: 69,
    reason: "Spot accumulation near $3,480 support. No leverage risk. Consistent with dip-buying pattern.",
    action: "Low urgency. Confirms demand zone, not a momentum signal.",
  },
];

export const mockOrderbook = {
  symbol: "BTCUSDT",
  midPrice: 67420,
  spread: 4,
  spreadBps: "0.006%",
  imbalance: +0.42,
  pressureSummary: {
    Now: "Bid pressure dominant. Bid wall at $67,400 holding since 14:20.",
    "5m": "Bid pressure increased over the last 5 minutes. Ask liquidity thinning above $67,450.",
    "1h": "Ask wall remains above current price at $68,000. Liquidity is tight but stable.",
  },
  asks: [
    { price: 67480, size: 1.24, usd: 83_475 },
    { price: 67470, size: 0.88, usd: 59_374 },
    { price: 67460, size: 2.41, usd: 162_578 },
    { price: 67450, size: 0.55, usd: 37_098 },
    { price: 67440, size: 3.20, usd: 215_808 },
    { price: 67430, size: 1.10, usd: 74_173 },
    { price: 67425, size: 0.74, usd: 49_895 },
    { price: 67422, size: 0.31, usd: 20_901 },
  ],
  bids: [
    { price: 67418, size: 0.42, usd: 28_316 },
    { price: 67415, size: 1.85, usd: 124_718 },
    { price: 67410, size: 0.63, usd: 42_468 },
    { price: 67400, size: 4.10, usd: 276_340 },
    { price: 67390, size: 1.22, usd: 82_216 },
    { price: 67380, size: 0.77, usd: 51_883 },
    { price: 67370, size: 2.60, usd: 175_162 },
    { price: 67350, size: 0.95, usd: 63_983 },
  ],
};

export const mockLiquidityZones = [
  { price: 68000, intensity: 95, side: "ASK", label: "Major Ask Wall",   desc: "Large resting sell orders. Hard resistance." },
  { price: 67500, intensity: 72, side: "ASK", label: "Ask Resistance",   desc: "Multiple sellers clustered. Watch for rejection." },
  { price: 67350, intensity: 88, side: "BID", label: "Major Bid Wall",   desc: "Held twice in the last hour. Key support level." },
  { price: 67000, intensity: 80, side: "BID", label: "Support Floor",    desc: "Demand zone aligning with daily structure." },
  { price: 66500, intensity: 61, side: "BID", label: "Demand Zone",      desc: "Lighter bids. Could be swept before reversal." },
  { price: 66200, intensity: 55, side: "BID", label: "Sweep Zone",       desc: "Likely liquidation magnet on a downside flush." },
  { price: 65800, intensity: 79, side: "BID", label: "Liquidity Gap",    desc: "Thin orderbook. Fast price movement expected here." },
];

export const mockPaperTrades = [
  {
    id: 1,
    symbol: "BTCUSDT",
    side: "LONG",
    entry: 67100,
    current: 67420,
    size: 0.5,
    pnl: 160,
    pnlPct: 0.48,
    status: "OPEN",
    setup: "Bid wall at 67,350 held. Entered on CVD confirmation.",
  },
  {
    id: 2,
    symbol: "SOLUSDT",
    side: "SHORT",
    entry: 160.50,
    current: 158.40,
    size: 12,
    pnl: 252,
    pnlPct: 1.31,
    status: "OPEN",
    setup: "Failed breakout above 160. Entered after ask wall rejection.",
  },
  {
    id: 3,
    symbol: "HYPEUSDT",
    side: "LONG",
    entry: 27.90,
    current: 28.74,
    size: 50,
    pnl: 42,
    pnlPct: 1.51,
    status: "WATCH",
    setup: "High momentum. Partial size. Waiting for $29 breakout confirmation.",
  },
];

export const mockJournal = [
  {
    date: "2026-05-31",
    symbol: "BTC",
    side: "LONG",
    pnl: 420,
    note: "Entered after bid wall held for 5m at $67,000. CVD turned positive. Closed at $67,700 target.",
  },
  {
    date: "2026-05-30",
    symbol: "ETH",
    side: "SHORT",
    pnl: -95,
    note: "Stop hit at $3,520. Underestimated bid absorption near support. Imbalance faded too slowly.",
  },
  {
    date: "2026-05-29",
    symbol: "SOL",
    side: "LONG",
    pnl: 210,
    note: "Liquidity sweep below $150 triggered entry. Clean reversal on high bid absorption. Closed at $155.80.",
  },
  {
    date: "2026-05-28",
    symbol: "HYPE",
    side: "LONG",
    pnl: 310,
    note: "Momentum trade. Entered early at $24.50 on volume spike. Reduced at $27 — left some on table.",
  },
];

export const roadmapItems = [
  {
    phase: "Q2 2026",
    title: "Private Beta Launch",
    status: "active",
    items: ["Live Orderbook Terminal", "Whale Alert Engine", "Basic Liquidity Maps"],
  },
  {
    phase: "Q3 2026",
    title: "Pro Features",
    status: "upcoming",
    items: ["AI Market Bias Engine", "Multi-Exchange Aggregation", "Paper Trading with P&L"],
  },
  {
    phase: "Q4 2026",
    title: "Premium Tier",
    status: "planned",
    items: ["Custom Alerts & Webhooks", "Historical Replay Mode", "Strategy Backtester"],
  },
  {
    phase: "2027",
    title: "Ecosystem",
    status: "planned",
    items: ["API Access", "Discord Bot", "Mobile App"],
  },
];
